[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
domain.workspace = true
db.workspace = true
ingestion.workspace = true
sqlx.workspace = true
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
chrono.workspace = true
